### ISSUE TITLE
Deprecated function: preg_replace()

### ISSUE THREAD

**Issue by jlcharette** [drupalwxt/site-wxt#29]
Good afternoon! I just installed a fresh site-wxt project via composer and running into a ton of deprecated warnings (which isn't the case when I install the default d9 distribution).

I am running the latest php/apache versions available (php8.1.8 & httpd 2.4.54).

![image](https://user-images.githubusercontent.com/44408591/178053685-142fefa0-7ab4-4030-b161-ae1f0a637f9b.png)

Is it that the WXT distribution is a couple version behind D9.4.2? How can I fix it?

Thank you and have a nice day.

**Comment by sylus** [comment]
This should be fixed now in latest release!
