### ISSUE TITLE
Confusion around why a tagged release is still using a dev build

### ISSUE THREAD

**Issue by williamroboly** [drupalwxt/site-wxt#33]
In the composer.json, for each tagged release, the version of drupalwxt used still denotes a DEV version. 

"drupalwxt/wxt": "4.4.x-dev",

Where as if I run the drupalwxt project creation composer command I land with a specific version:

"drupalwxt/wxt": "4.4.0",

Why does this template not do the same thing as the core project?

I find this confusing.

**Comment by sylus** [comment]
My apologies this was a mistake on the release action.

I think the following fix should address this :)

https://github.com/drupalwxt/wxt/commit/114e5df923aa0c446fe413431acc0428d00cea19
